name: Release hotfix

on:
  push:
    branches: [hotfix]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: hotfix

      - name: Prepare build
        run: ./util/build-prepare.sh

      - name: Build for all platforms and archs
        run: ./util/build-all.sh

      - name: Prepare tests
        run: ./util/test-prepare.sh

      - name: Run UTs
        run: ./util/test-unit.sh

      - name: Run static analysis (cppcheck)
        run: ./util/test-cppcheck.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./build/release

  build_windows_installer:
    needs: build_and_test

    runs-on: windows-2019

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: hotfix

      - name: Fetch artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Copy .exe and license to installer dir
        run: |
          copy husarnet.exe windows\installer
          copy LICENSE.txt windows\installer
        shell: cmd

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" windows\installer\script.iss
        shell: cmd

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: windows_installer
          path: windows\installer\Output\husarnet-setup.exe

  # release_github:
  #   needs: [build_and_test, build_windows_installer]

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Fetch linux packages
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: packages

  #     - name: Fetch windows installer
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: windows_installer

  #     - uses: marvinpinto/action-automatic-releases@latest
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         draft: true
  #         prerelease: false
  #         automatic_release_tag: ${{ github.ref_name }}
  #         files: |
  #           *.deb
  #           *.tar
  #           *.rpm
  #           *.exe

  # push_docker_images:
  #   needs: build_and_test

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #       with:
  #         version: latest

  #     - name: Login to Docker Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: docker.io
  #         username: ${{ secrets.HNETUSER_DOCKERHUB_LOGIN }}
  #         password: ${{ secrets.HNETUSER_DOCKERHUB_PASSWORD }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./unix/docker-misc/Dockerfile
  #         platforms: linux/arm64/v8, linux/amd64, linux/arm/v7
  #         push: true
  #         tags: husarnet/husarnet
  #         #cache-from: type=registry,ref=
  #         #cache-to: type=inline

  release_prod:
    needs: [build_and_test, build_windows_installer]

    runs-on: [self-hosted, linux, prod]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: hotfix

      - name: Fetch artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Fetch windows installer
        uses: actions/download-artifact@v2
        with:
          name: windows_installer

      - name: Deploy to main Husarnet repository
        run: ./util/deploy.sh main
